### ISSUE TITLE
Minimal permissions needed for an IAM user?

### ISSUE THREAD

**Issue by chadoh** [import-io/s3-deploy#33]
Thanks for `s3-deploy`; great library.

I'm trying to set up a new AWS user with minimal permissions for deploying with this script. Giving it full access to all S3 functions doesn't seem to be sufficient. Any idea what else it would need?

**Comment by achingbrain** [comment]
I've got it working with:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:PutObjectAcl"
            ],
            "Resource": "arn:aws:s3:::BUCKET_NAME/*"
        }
    ]
}
```

Replace `BUCKET_NAME` with, you know, your bucket name.

**Comment by victorbartel** [comment]
No, it does not work, it shows:
```
Unexpected error: (Forbidden) null, aborting upload for FILE
```
Can you please specify a correct minimal permissions list in the documentation? Thanks.

**Comment by rm-rf-etc** [comment]
These are the correct permissions. These are the permissions I'm using in my policy, and I was able to verify this works using aws cli.
```aws s3api put-object --bucket MY_BUCKET --key index.html --body ./index.html```
```aws s3api delete-object --bucket MY_BUCKET --key index.html```

However, s3-deploy doesn't work for me right now.

```
$ npx s3-deploy './build/**' --cwd './build/' --region us-east-1 --bucket MY_BUCKET

Upload error: AccessDenied: Access Denied (AccessDenied: Access Denied
    at Request.extractError (/Users/rob/projects/MY_PROJECT/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (/Users/rob/projects/MY_PROJECT/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/rob/projects/MY_PROJECT/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/rob/projects/MY_PROJECT/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/rob/projects/MY_PROJECT/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/rob/projects/MY_PROJECT/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/rob/projects/MY_PROJECT/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/rob/projects/MY_PROJECT/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/rob/projects/MY_PROJECT/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/rob/projects/MY_PROJECT/node_modules/aws-sdk/lib/sequential_executor.js:116:18))
```

I have set my credentials in the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, but these appear to be ignored.

**Comment by domderen** [comment]
Hey, this might be because of AWS'es new policy to disable uploading files that would be available publicly. New S3 buckets are by default configrured to disallow uploading files, if they would be available publicly. `s3-deploy` on the other hand is by default uploading files with public access, which might cause that error. I would recommend trying again your command with `--private` flag added.

**Comment by rm-rf-etc** [comment]
@domderen, that was it! Uploads work! I would have thought that setting the files to private would make theme inaccessible but they are serving just fine. The bucket is configured for hosting a static site and all appears to be working. Thanks!

**Comment by domderen** [comment]
Glad to hear it! Would be great to add to the readme information about Amazon's new default `--private` requirement.
