### ISSUE TITLE
babel-polyfill is a missing dependency

### ISSUE THREAD

**Issue by mavimo** [import-io/s3-deploy#48]
Actually `babel-polyfill` is a dev dependency, than when we install `s3-deploy` in prod mode it break the app with:
```
npm install s3-deploy
node_modules/.bin/s3-deploy ./docs/*.* --cwd ./docs/ --filePrefix docs --gzip --cache 31536000 --immutable --etag --region $S3_REGION --bucket $S3_BUCKET
```
we see
```
module.js:472
    throw err;
    ^

Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/drone/src/github.com/mavimo/demo/node_modules/s3-deploy/dist/index.js:3:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

We have two options:
 1. remove `babel-polyfill`
 1. include `babel-polyfill` as `dependency` instead of `devDependency`

I start to investigate the first solution since seems that `babel-polifil` is explicitally removed from deps in 203f456b4f16679bc1e43bb2a39b2832c00f52ea, I'll keep you update.

**Comment by taddei** [comment]
our pipeline started failing for the same reason. we installed `babel-polyfill` and everything worked as expected.
```npm i s3-deploy babel-polyfill```

**Comment by mavimo** [comment]
@taddei we pinned to 0.10 with `npm i s3-deploy@0.10`, but we will like to have possibility to invalidate cloudfront without extra step in CI ;)

**Comment by domderen** [comment]
Hey, thanks everyone for a quick info, and PR to fix it. It should be fine in `v0.11.1`.
