### ISSUE TITLE
Cloudfront handler can't handle Access keys with a / in them

### ISSUE THREAD

**Issue by PandelisZ** [import-io/s3-deploy#51]
```sh
{ IncompleteSignature: 'REDACTED/REDACTED/us-east-1/cloudfront/aws4_request' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=$AWS_ACCESS_KEY_ID/REDACTED/us-east-1/cloudfront/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=REDACTED'.
    at Request.extractError (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/protocol/rest_xml.js:44:29)
    at Request.callListeners (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: '\'REDACTED/REDACTED/us-east-1/cloudfront/aws4_request\' not a valid key=value pair (missing equal-sign) in Authorization header: \'AWS4-HMAC-SHA256 Credential=$AWS_ACCESS_KEY_ID/REDACTED/us-east-1/cloudfront/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=REDACTED\'.',
  code: 'IncompleteSignature',
  time: 2018-05-04T14:24:16.402Z,
  requestId: 'd35c588f-4fa6-11e8-becc-375991b36dec',
  statusCode: 403,
  retryable: false,
  retryDelay: 0.912777494578032 }
(node:1094) UnhandledPromiseRejectionWarning: Invalidate error: IncompleteSignature: 'REDACTED/REDACTED/us-east-1/cloudfront/aws4_request' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=$AWS_ACCESS_KEY_ID/REDACTED/us-east-1/cloudfront/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=REDACTED'. (IncompleteSignature: 'REDACTED/REDACTED/us-east-1/cloudfront/aws4_request' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=$AWS_ACCESS_KEY_ID/20180504/us-east-1/cloudfront/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=REDACTED'.
    at Request.extractError (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/protocol/rest_xml.js:44:29)
    at Request.callListeners (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/sequential_executor.js:115:18))
(node:1094) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1094) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by domderen** [comment]
Hey, this looks more like an issue with the AWS SDK, rather than s3-deploy, as we are just using standard aws-sdk package to use CloudFront API. Do you agree?

**Comment by PandelisZ** [comment]
I'll investigate. It could be the way I stored the string in the enviroment variable.
