### ISSUE TITLE
Return non-zero exit code if file does not upload

### ISSUE THREAD

**Issue by jamsea** [import-io/s3-deploy#60]
Is there a way to return a non zero exit code if a file doesn't get uploaded? E.g. If I have something like this:

```
s3-deploy './dist/$npm_package_name.$npm_package_version.min.js' --cwd './dist/' --region us-west-2 --bucket BUCKET --gzip --preventUpdates --immutable --ext js
```
And the file exists on s3, or the file couldn't be found on the developer's machine I want an error to be thrown and a non-zero exit code to be returned. That way the CI/CD deploy could fail on Jenkins.

If there's no way to do this now, could you point me in the right direction where this change would be? I could make a PR

**Comment by toupeira** [comment]
I'd really like this as well :+1: 

I saw that `src/index.js` tries to handle exceptions and do `process.exit(1)`, but it doesn't seem to catch all exceptions like missing permissions.

A workaround I found is to run `node --throw-deprecation node_modules/s3-deploy/.bin/s3-deploy` instead, this seems to trigger a non-zero exit code in the cases I'm interested in (using NodeJS 8.11.3).

**Comment by toupeira** [comment]
Here are two cases that trigger errors but `s3-deploy` still returns success messages ("Upload finished") and an exit code of 0.

Also note that this is on NodeJS 8.11.3, earlier versions might not show the `UnhandledPromiseRejectionWarning`.

(`[SNIP]` --> sensitive information removed)

- Missing `--bucket` argument:
  ```
  Unexpected error: (MissingRequiredParameter) Missing required key 'Bucket' in params, aborting upload for [SNIP]
  Upload finished
  (node:6697) UnhandledPromiseRejectionWarning: Upload error: MissingRequiredParameter: Missing required key 'Bucket' in params (MissingRequiredParameter: Missing required key 'Bucket' in params
      at ParamValidator.fail ([SNIP]/node_modules/aws-sdk/lib/param_validator.js:50:37)
      at ParamValidator.validateStructure ([SNIP]/node_modules/aws-sdk/lib/param_validator.js:61:14)
      at ParamValidator.validateMember ([SNIP]/node_modules/aws-sdk/lib/param_validator.js:88:21)
      at ParamValidator.validate ([SNIP]/node_modules/aws-sdk/lib/param_validator.js:34:10)
      at Request.VALIDATE_PARAMETERS ([SNIP]/node_modules/aws-sdk/lib/event_listeners.js:89:42)
      at Request.callListeners ([SNIP]/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
      at callNextListener ([SNIP]/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
      at [SNIP]/node_modules/aws-sdk/lib/event_listeners.js:75:9
      at finish ([SNIP]/node_modules/aws-sdk/lib/config.js:299:7)
      at [SNIP]/node_modules/aws-sdk/lib/config.js:315:9)
  (node:6697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 93)
  (node:6697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  Done in 0.46s.
  ```

- Undefined `$AWS_ACCESS_KEY_ID` or `$AWS_SECRET_ACCESS_KEY`:
  ```
  Unexpected error: (CredentialsError) Missing credentials in config, aborting upload for [SNIP]
  Upload finished
  (node:11773) UnhandledPromiseRejectionWarning: Upload error: TimeoutError: Missing credentials in config (TimeoutError: Missing credentials in config
      at ClientRequest.<anonymous> ([SNIP]/node_modules/aws-sdk/lib/http/node.js:56:34)
      at Object.onceWrapper (events.js:313:30)
      at emitNone (events.js:106:13)
      at ClientRequest.emit (events.js:208:7)
      at Socket.emitTimeout (_http_client.js:706:34)
      at Object.onceWrapper (events.js:313:30)
      at emitNone (events.js:106:13)
      at Socket.emit (events.js:208:7)
      at Socket._onTimeout (net.js:410:8)
      at ontimeout (timers.js:498:11))
  (node:11773) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  (node:11773) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  Done in 2.46s.
  ```

**Comment by toupeira** [comment]
@domderen I'd be happy to submit a PR if you could give me your opinion and some pointers :)

**Comment by domderen** [comment]
That's actually interesting that the AWS calls are failing with an unhandled rejection. Those should be caught here: https://github.com/import-io/s3-deploy/blob/ac955232f62d7024025f7dc6b248cb1ba9322edb/src/index.js#L115 and program should exit with status code 1.

If you have some time to debug that case and see why in those cases we get unhandled rejection, that would be much appreciated.

**Comment by toupeira** [comment]
As far as I can tell, since the rejection is unhandled it's not caught by this `try` block.

Adding this:

```js
process.on('unhandledRejection', error => { throw error });
```

after https://github.com/import-io/s3-deploy/blob/ac955232f62d7024025f7dc6b248cb1ba9322edb/src/index.js#L104 does result in an exit code of 1. I'll submit a PR if you think that's an acceptable workaround.

The real fix (assuming it's not a bug in `aws-sdk` itself) would probably be to find out which promise is unhandled, but I'm not sure how to go about debugging that, and also how to quickly test it without having to rebuild from `src` to `dist` :)
