### ISSUE TITLE
--invalidate requires a value?

### ISSUE THREAD

**Issue by achingbrain** [import-io/s3-deploy#95]
For `--invalidate` the readme says:

>  Defaults to ['/']

but if I specify `--invalidate` without a value I get:

```console
$ s3-deploy ...other args... --distId some-dist-id --invalidate
... lots of output here ...
TypeError: options.invalidate.split is not a function
    at _callee3$ (/home/circleci/repo/node_modules/s3-deploy/dist/deploy.js:432:57)
    at tryCatch (/home/circleci/repo/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/circleci/repo/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/circleci/repo/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at onFulfilled (/home/circleci/repo/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

The following works as expected:

```console
$ s3-deploy ...other args... --distId some-dist-id --invalidate /
```

**Comment by raimon-segura** [comment]
It doesn't work for me, I should add a "typeof" validation in line 432 to deploy to s3
`
            if (options.hasOwnProperty('invalidate') && (typeof options.invalidate != "undefined") ) {
              cfOptions.invalidate = options.invalidate.split(' ');
            }
`

thanks!
